
export const SCRIPT_OPCODES: {[key: number]: {name: string, format: string, desc: string}} = {
    0: { name: 'EV_EVAL', format: 'eval', desc: 'Condition Check' },
    1: { name: 'EV_JUMP', format: 'u16', desc: 'Jump' },
    2: { name: 'EV_RETURN', format: '', desc: 'Return' },
    3: { name: 'EV_MESSAGE', format: 'u16', desc: 'Show Message' },
    4: { name: 'EV_LERPSPRITE', format: 'custom_lerp', desc: 'Move Sprite' }, // CHANGED: Variable length
    5: { name: 'EV_STARTCINEMATIC', format: 'u8', desc: 'Cinematic' },
    6: { name: 'EV_SETSTATE', format: 'u8 s16', desc: 'Set Game State' },
    7: { name: 'EV_CALL_FUNC', format: 'u16', desc: 'Call Script' },
    8: { name: 'EV_ITEM_COUNT', format: 'u16 u8', desc: 'Check Item Count' },
    9: { name: 'EV_TILE_EMPTY', format: 'u16 u8', desc: 'Check Tile Empty' },
    10: { name: 'EV_WEAPON_EQUIPPED', format: 'u8', desc: 'Check Weapon' },
    11: { name: 'EV_CHANGE_MAP', format: 'u8 u16', desc: 'Change Map' },
    12: { name: 'EV_CAMERA_STR', format: 'u16 u16', desc: 'Camera String' },
    13: { name: 'EV_DIALOG', format: 'u8 u8', desc: 'Show Dialog' },
    14: { name: 'EV_WAIT', format: 'u8', desc: 'Wait' },
    15: { name: 'EV_GOTO', format: 'u16', desc: 'Goto' },
    16: { name: 'EV_ABORT_MOVE', format: '', desc: 'Stop Movement' },
    17: { name: 'EV_ENTITY_FRAME', format: 'u8 u8 u8', desc: 'Set Entity Frame' },
    18: { name: 'EV_ADV_CAMERAKEY', format: 'u8', desc: 'Camera Keyframe' },
    19: { name: 'EV_DAMAGEMONSTER', format: 'u8 s8', desc: 'Damage Monster' },
    20: { name: 'EV_DAMAGEPLAYER', format: 's8 s8 s8', desc: 'Damage Player' },
    21: { name: 'EV_DOOROP', format: 'u16', desc: 'Door Operation' },
    22: { name: 'EV_MONSTERFLAGOP', format: 'u8 u8', desc: 'Monster Flags' },
    23: { name: 'EV_EVENTOP', format: 'u16', desc: 'Modify Event' },
    24: { name: 'EV_HIDE', format: 'u8', desc: 'Hide/Show Entity' },
    25: { name: 'EV_DROPITEM', format: 'u16 u8', desc: 'Spawn/Drop Item' },
    26: { name: 'EV_PREVSTATE', format: 'u8', desc: 'Dec State Var' },
    27: { name: 'EV_NEXTSTATE', format: 'u8', desc: 'Inc State Var' },
    28: { name: 'EV_WAKEMONSTER', format: 'u8', desc: 'Wake Monster' },
    29: { name: 'EV_SHOW_PLAYERATTACK', format: 'u8', desc: 'Show Weapon Anim' },
    30: { name: 'EV_MONSTER_PARTICLES', format: 'u8', desc: 'Bleed Effect' },
    31: { name: 'EV_SPAWN_PARTICLES', format: 'u8 u16 u8', desc: 'Spawn Particles' },
    32: { name: 'EV_FADEOP', format: 'u16', desc: 'Screen Fade' },
    33: { name: 'EV_GIVEITEM', format: 'u8 u8 s8', desc: 'Give Player Item' },
    34: { name: 'EV_NAMEENTITY', format: 'u8 u8', desc: 'Rename Entity' },
    35: { name: 'EV_DROPMONSTERITEM', format: 'drop_monster_item', desc: 'Drop Loot' },
    36: { name: 'EV_SETDEATHFUNC', format: 'u8 s16', desc: 'OnDeath Trigger' },
    37: { name: 'EV_PLAYSOUND', format: 'u8 u8', desc: 'Play Sound' },
    38: { name: 'EV_NPCCHAT', format: 'u16', desc: 'NPC Chat Bubble' },
    39: { name: 'EV_STOCKSTATION', format: '', desc: 'Restock Vending' },
    40: { name: 'EV_LERPFLAT', format: 'u8 u16', desc: 'Move Flat' },
    41: { name: 'EV_GIVELOOT', format: 'var_loot_list', desc: 'Loot Screen' },
    42: { name: 'EV_MARKTILE', format: 'u16', desc: 'Mark AutoMap' },
    43: { name: 'EV_UPDATEJOURNAL', format: 'u8 u8', desc: 'Update Quest' },
    44: { name: 'EV_BRIBE_ENTITY', format: '', desc: 'Bribe' },
    45: { name: 'EV_PLAYER_ADD_STAT', format: 'u8', desc: 'Buff Player' },
    46: { name: 'EV_PLAYER_ADD_RECIPE', format: 'u16', desc: 'Add Recipe' },
    47: { name: 'EV_RESPAWN_MONSTER', format: 'u16 u8 u8', desc: 'Respawn' },
    48: { name: 'EV_SCREEN_SHAKE', format: 'u16', desc: 'Shake Screen' },
    49: { name: 'EV_SPEECHBUBBLE', format: 'u16 u8', desc: 'Show Bubble' },
    50: { name: 'EV_AWARDSECRET', format: '', desc: 'Secret Found' },
    51: { name: 'EV_AIGOAL', format: 'u16 u8', desc: 'Set AI Goal' },
    52: { name: 'EV_ADVANCETURN', format: '', desc: 'Next Turn' },
    53: { name: 'EV_MINIGAME', format: 's8 s8 s8 s8', desc: 'Start Minigame' },
    54: { name: 'EV_ENDMINIGAME', format: '', desc: 'End Minigame' },
    55: { name: 'EV_ENDROUND', format: '', desc: 'End Round' },
    56: { name: 'EV_PLAYERATTACK', format: 'u16', desc: 'Force Attack' },
    57: { name: 'EV_SET_FOG_COLOR', format: 's32', desc: 'Set Fog' },
    58: { name: 'EV_LERP_FOG', format: 's32', desc: 'Lerp Fog' },
    59: { name: 'EV_LERPSPRITEOFFSET', format: 'u8 u8 s32', desc: 'Lerp Offset' },
    60: { name: 'EV_DISABLED_WEAPONS', format: 's16', desc: 'Disable Weapons' },
    61: { name: 'EV_LERPSCALE', format: 'u16 u16 u8', desc: 'Scale Sprite' },
    62: { name: 'EV_GIVEAWARD', format: '', desc: 'Award' },
    65: { name: 'EV_STARTMIXING', format: '', desc: 'Mix Items' },
    66: { name: 'EV_DEBUGPRINT', format: 'debug_str', desc: 'Debug Log' },
    67: { name: 'EV_GOTO_MENU', format: 'u8', desc: 'Open Menu' },
    68: { name: 'EV_START_INTERCINEMATIC', format: 'u8', desc: 'Cinematic' },
    69: { name: 'EV_TURN_PLAYER', format: 'u8', desc: 'Turn Player' },
    70: { name: 'EV_STATUS_EFFECT', format: 'u8 u8', desc: 'Status Effect' },
    71: { name: 'EV_JOURNAL_TILE', format: 'u8 u8 u8', desc: 'Quest Tile' },
    72: { name: 'EV_MAKE_CORPSE', format: 'u16 u8 u8', desc: 'Create Corpse' },
    73: { name: 'EV_INVENTORY_OP', format: 'u8', desc: 'Mod Inventory' },
    74: { name: 'EV_END_GAME', format: '', desc: 'Game Over' },
    75: { name: 'EV_LERPSPRITEPARABOLA', format: 's32 u16', desc: 'Jump Sprite' },
    76: { name: 'EV_TOGGLE_OVERLAY', format: '', desc: 'Toggle UI' },
    77: { name: 'EV_FOG_AFFECTS_SKYMAP', format: 'u8', desc: 'Fog Sky' },
    78: { name: 'EV_ENABLE_HELP', format: 'u8', desc: 'Enable Help' },
    79: { name: 'EV_SET_MM_RENDER_HACK', format: 'u8', desc: 'Boss Hack' },
    80: { name: 'EV_START_ARMORREPAIR', format: '', desc: 'Repair Armor' },
    81: { name: 'EV_FORCE_BOT_RETURN', format: '', desc: 'Recall Bot' },
    82: { name: 'EV_UNMARKTILE', format: 'u16', desc: 'Unmark Map' },
    83: { name: 'EV_ASSIGN_LOOTSET', format: 'u16 var_loot_list', desc: 'Assign Loot' },
    84: { name: 'EV_START_TARGETPRACTICE', format: 'u16', desc: 'Target Practice' },
    85: { name: 'EV_GIVE_AUTOMAP', format: '', desc: 'Give Map' },
    86: { name: 'EV_ANGER_VIOS', format: 'u8', desc: 'Anger Boss' },
    87: { name: 'EV_UNHIDE_AUTOMAP', format: 'u8 u8 u8 u8', desc: 'Reveal Map' },
    88: { name: 'EV_HIDE_AUTOMAP', format: 'u8 u8 u8 u8', desc: 'Hide Map' },
    89: { name: 'EV_PORTAL_EVENT', format: 'u8', desc: 'Portal FX' },
    90: { name: 'EV_PITCH_CONTROL', format: 'u16', desc: 'Set Pitch' },
    91: { name: 'EV_USED_CHAINSAW', format: '', desc: 'Chainsaw Event' },
    92: { name: 'EV_ENTITY_BREATHES', format: 'u8 u8', desc: 'Breathing' },
    93: { name: 'EV_DESTROY_PLAYER', format: 's8', desc: 'Kill Player' },
    94: { name: 'EV_START_TREADMILL', format: '', desc: 'Treadmill' },
    95: { name: 'EV_LERPSPRITEPARABOLA_SCALE', format: 's32 u16 u8', desc: 'Jump Scale' },
    96: { name: 'EV_SET_CALDEX_RENDER_HACK', format: 'u8', desc: 'Render Hack' },
};
