import { Component, ElementRef, input, output, signal, viewChild, effect } from '@angular/core';
import { floodFillPixels, moveSelectionPixels, paintBrush, rasterizeLine, type CanvasPoint, type PixelBuffer } from '../../texture-viewer/texture-canvas/texture-canvas-interaction';
import { indexedToRgba, type DecodedPng } from '../../../core/png-codec';
export type ImageTool='pencil'|'brush'|'fill'|'select';
@Component({selector:'app-image-canvas',standalone:true,template:`<canvas #canvas class="image-pixelated border border-neutral-700 touch-none" [style.width.px]="model().width*zoom()" [style.height.px]="model().height*zoom()" (pointerdown)="down($event)" (pointermove)="move($event)" (pointerup)="up($event)" (pointercancel)="cancel($event)"></canvas>`,styles:['.image-pixelated{image-rendering:pixelated}']})
export class ImageCanvasComponent{
 readonly model=input.required<DecodedPng>();readonly tool=input<ImageTool>('pencil');readonly zoom=input(8);readonly brushSize=input(1);readonly paletteIndex=input(0);readonly rgba=input<[number,number,number,number]>([255,255,255,255]);readonly changed=output<PixelBuffer>();private readonly canvas=viewChild.required<ElementRef<HTMLCanvasElement>>('canvas');private last:CanvasPoint|null=null;private origin:CanvasPoint|null=null;private selection:{x:number;y:number;width:number;height:number}|null=null;private working:PixelBuffer|null=null;
 constructor(){effect(()=>{this.model();this.render();});}
 private point(e:PointerEvent):CanvasPoint{const rect=this.canvas().nativeElement.getBoundingClientRect(),m=this.model();return{x:Math.max(0,Math.min(m.width-1,Math.floor((e.clientX-rect.left)*m.width/rect.width))),y:Math.max(0,Math.min(m.height-1,Math.floor((e.clientY-rect.top)*m.height/rect.height)))}};
 private color(){return this.model().indexed?[this.paletteIndex()]:this.rgba()}
 down(e:PointerEvent){if(e.button!==0)return;this.canvas().nativeElement.setPointerCapture(e.pointerId);const p=this.point(e);this.last=p;this.origin=p;this.working=this.model().pixels.slice() as PixelBuffer;if(this.tool()==='fill'){this.working=floodFillPixels(this.working,this.model().width,this.model().height,p,this.color(),this.model().indexed?1:4);this.commit();}else if(this.tool()!=='select')this.draw(p,p);}
 move(e:PointerEvent){if(!this.last||!this.working||!(e.buttons&1))return;const p=this.point(e);if(this.tool()==='select'&&this.selection){const dx=p.x-this.last.x,dy=p.y-this.last.y;this.working=moveSelectionPixels(this.working,this.model().width,this.model().height,this.selection,this.selection.x+dx,this.selection.y+dy,this.model().indexed?this.paletteIndex():[0,0,0,0],this.model().indexed?1:4);this.selection={...this.selection,x:this.selection.x+dx,y:this.selection.y+dy};this.last=p;this.render(this.working);return;}if(this.tool()!=='select')this.draw(this.last,p);this.last=p;}
 up(e:PointerEvent){if(this.tool()==='select'&&this.origin){const p=this.point(e);if(!this.selection)this.selection={x:Math.min(p.x,this.origin.x),y:Math.min(p.y,this.origin.y),width:Math.abs(p.x-this.origin.x)+1,height:Math.abs(p.y-this.origin.y)+1};else this.commit();}else if(this.working)this.commit();this.last=null;this.origin=null;this.canvas().nativeElement.releasePointerCapture(e.pointerId);}
 cancel(e:PointerEvent){this.last=null;this.origin=null;this.working=null;if(this.canvas().nativeElement.hasPointerCapture(e.pointerId))this.canvas().nativeElement.releasePointerCapture(e.pointerId);this.render();}
 private draw(a:CanvasPoint,b:CanvasPoint){for(const p of rasterizeLine(a,b))this.working=paintBrush(this.working!,this.model().width,this.model().height,p,this.color(),this.tool()==='brush'?this.brushSize():1,this.model().indexed?1:4);this.render(this.working!)}
 private commit(){if(this.working)this.changed.emit(this.working);this.working=null;}
 private render(pixels=this.model().pixels){queueMicrotask(()=>{const canvas=this.canvas().nativeElement,m=this.model();canvas.width=m.width;canvas.height=m.height;const rgba=m.indexed?indexedToRgba({...m,pixels}):pixels as Uint8ClampedArray;canvas.getContext('2d')!.putImageData(new ImageData(new Uint8ClampedArray(rgba),m.width,m.height),0,0);});}
}
