export type PngColorKind = 'indexed' | 'grayscale' | 'truecolor' | 'grayscale-alpha' | 'truecolor-alpha';
export interface PngInfo { width: number; height: number; bitDepth: number; colorType: number; kind: PngColorKind; indexed: boolean; hasAlpha: boolean; palette?: Uint8Array; transparency?: Uint8Array; }
export interface DecodedPng extends PngInfo { pixels: Uint8Array | Uint8ClampedArray; originalBytes: ArrayBuffer; }

const signature = new Uint8Array([137,80,78,71,13,10,26,10]);
function chunks(buffer: ArrayBuffer) { const bytes=new Uint8Array(buffer), view=new DataView(buffer), out:{type:string;data:Uint8Array}[]=[]; let p=8; while(p+12<=bytes.length){const n=view.getUint32(p), end=p+12+n;if(end>bytes.length)throw new Error('Truncated PNG chunk');const type=String.fromCharCode(...bytes.subarray(p+4,p+8));out.push({type,data:bytes.slice(p+8,p+8+n)});p=end;if(type==='IEND')break;} return out; }
/** Inspects PNG chunks without decoding/re-encoding pixel data. */
export function inspectPng(buffer:ArrayBuffer):PngInfo { const bytes=new Uint8Array(buffer);if(bytes.length<33||!signature.every((v,i)=>bytes[i]===v))throw new Error('Not a PNG image');const view=new DataView(buffer),width=view.getUint32(16),height=view.getUint32(20),bitDepth=bytes[24],colorType=bytes[25];if(!width||!height||width>4096||height>4096)throw new Error(`Unsupported PNG dimensions ${width}x${height}`);const kinds:Record<number,PngColorKind>={0:'grayscale',2:'truecolor',3:'indexed',4:'grayscale-alpha',6:'truecolor-alpha'},kind=kinds[colorType];if(!kind)throw new Error(`Unsupported PNG color type ${colorType}`);let palette:Uint8Array|undefined,transparency:Uint8Array|undefined;for(const c of chunks(buffer)){if(c.type==='PLTE')palette=c.data;if(c.type==='tRNS')transparency=c.data;}if(colorType===3&&!palette)throw new Error('Indexed PNG is missing PLTE');return {width,height,bitDepth,colorType,kind,indexed:colorType===3,hasAlpha:colorType===4||colorType===6||!!transparency?.some(a=>a!==255),palette,transparency}; }
async function transform(data:Uint8Array, format:'deflate'|'deflate-raw', decompress:boolean){const stream=decompress?new DecompressionStream(format):new CompressionStream(format);const response=new Response(new Blob([data as BlobPart]).stream().pipeThrough(stream));return new Uint8Array(await response.arrayBuffer());}
function paeth(a:number,b:number,c:number){const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;}
export async function decodePng(buffer:ArrayBuffer):Promise<DecodedPng>{const info=inspectPng(buffer);if(info.bitDepth!==8&&!(info.indexed&&[1,2,4].includes(info.bitDepth)))throw new Error(`Unsupported PNG bit depth ${info.bitDepth}`);const cs=chunks(buffer),idat=cs.filter(c=>c.type==='IDAT').map(c=>c.data),packed=new Uint8Array(idat.reduce((n,c)=>n+c.length,0));let at=0;idat.forEach(c=>{packed.set(c,at);at+=c.length});const raw=await transform(packed,'deflate',true);const samples=info.colorType===0?1:info.colorType===2?3:info.colorType===3?1:info.colorType===4?2:4,rowBytes=Math.ceil(info.width*samples*info.bitDepth/8),bpp=Math.max(1,Math.ceil(samples*info.bitDepth/8)),rows=new Uint8Array(rowBytes*info.height);let input=0;for(let y=0;y<info.height;y++){const filter=raw[input++],row=y*rowBytes;for(let x=0;x<rowBytes;x++){const value=raw[input++],left=x>=bpp?rows[row+x-bpp]:0,up=y?rows[row-rowBytes+x]:0,upperLeft=y&&x>=bpp?rows[row-rowBytes+x-bpp]:0;rows[row+x]=(value+(filter===1?left:filter===2?up:filter===3?Math.floor((left+up)/2):filter===4?paeth(left,up,upperLeft):0))&255;}}
let pixels:Uint8Array|Uint8ClampedArray;if(info.indexed){pixels=new Uint8Array(info.width*info.height);const mask=(1<<info.bitDepth)-1;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const bit=x*info.bitDepth;(pixels as Uint8Array)[y*info.width+x]=(rows[y*rowBytes+(bit>>3)]>>(8-info.bitDepth-(bit&7)))&mask;}}else{pixels=new Uint8ClampedArray(info.width*info.height*4);for(let i=0;i<info.width*info.height;i++){let r=0,g=0,b=0,a=255;if(info.colorType===0)r=g=b=rows[i];else if(info.colorType===2){r=rows[i*3];g=rows[i*3+1];b=rows[i*3+2];}else if(info.colorType===4){r=g=b=rows[i*2];a=rows[i*2+1];}else {r=rows[i*4];g=rows[i*4+1];b=rows[i*4+2];a=rows[i*4+3];}(pixels as Uint8ClampedArray).set([r,g,b,a],i*4);}}return {...info,pixels,originalBytes:buffer.slice(0)};}
let crcTable:Uint32Array|undefined;function crc(data:Uint8Array){crcTable??=Uint32Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0});let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function chunk(type:string,data:Uint8Array){const out=new Uint8Array(data.length+12),v=new DataView(out.buffer);v.setUint32(0,data.length);out.set([...type].map(c=>c.charCodeAt(0)),4);out.set(data,8);v.setUint32(data.length+8,crc(out.subarray(4,data.length+8)));return out;}
export async function encodeIndexedPng(model:Pick<DecodedPng,'width'|'height'|'bitDepth'|'pixels'|'palette'|'transparency'>):Promise<ArrayBuffer>{const {width,height,bitDepth}=model;if(!model.palette||![1,2,4,8].includes(bitDepth))throw new Error('Invalid indexed PNG model');const rowBytes=Math.ceil(width*bitDepth/8),raw=new Uint8Array((rowBytes+1)*height),mask=(1<<bitDepth)-1;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const value=model.pixels[y*width+x];if(value>mask)throw new Error(`Palette index ${value} exceeds bit depth`);const bit=x*bitDepth;raw[y*(rowBytes+1)+1+(bit>>3)]|=value<<(8-bitDepth-(bit&7));}const compressed=await transform(raw,'deflate',false),ihdr=new Uint8Array(13),v=new DataView(ihdr.buffer);v.setUint32(0,width);v.setUint32(4,height);ihdr[8]=bitDepth;ihdr[9]=3;const parts=[signature,chunk('IHDR',ihdr),chunk('PLTE',model.palette),...(model.transparency?.length?[chunk('tRNS',model.transparency)]:[]),chunk('IDAT',compressed),chunk('IEND',new Uint8Array())],out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let at=0;parts.forEach(p=>{out.set(p,at);at+=p.length});return out.buffer;}
export function indexedToRgba(model:Pick<DecodedPng,'pixels'|'palette'|'transparency'>):Uint8ClampedArray{const palette=model.palette!;const out=new Uint8ClampedArray(model.pixels.length*4);for(let i=0;i<model.pixels.length;i++){const index=model.pixels[i];out.set([palette[index*3]??0,palette[index*3+1]??0,palette[index*3+2]??0,model.transparency?.[index]??255],i*4);}return out;}
export async function encodeRgbaPng(width:number,height:number,pixels:Uint8Array):Promise<ArrayBuffer>{if(pixels.length!==width*height*4)throw new Error('Invalid RGBA pixel count');const raw=new Uint8Array(height*(width*4+1));for(let y=0;y<height;y++)raw.set(pixels.subarray(y*width*4,(y+1)*width*4),y*(width*4+1)+1);const compressed=await transform(raw,'deflate',false),ihdr=new Uint8Array(13),v=new DataView(ihdr.buffer);v.setUint32(0,width);v.setUint32(4,height);ihdr[8]=8;ihdr[9]=6;const parts=[signature,chunk('IHDR',ihdr),chunk('IDAT',compressed),chunk('IEND',new Uint8Array())],out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let at=0;parts.forEach(p=>{out.set(p,at);at+=p.length});return out.buffer;}
